// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.1
// source: api/proto/v1/report.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ReportRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SessionId      string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	ReporterId     string                 `protobuf:"bytes,2,opt,name=reporter_id,json=reporterId,proto3" json:"reporter_id,omitempty"`
	ReportedUserId string                 `protobuf:"bytes,3,opt,name=reported_user_id,json=reportedUserId,proto3" json:"reported_user_id,omitempty"`
	Reason         string                 `protobuf:"bytes,4,opt,name=reason,proto3" json:"reason,omitempty"`
	ChatLogsJson   string                 `protobuf:"bytes,5,opt,name=chat_logs_json,json=chatLogsJson,proto3" json:"chat_logs_json,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ReportRequest) Reset() {
	*x = ReportRequest{}
	mi := &file_api_proto_v1_report_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportRequest) ProtoMessage() {}

func (x *ReportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_report_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportRequest.ProtoReflect.Descriptor instead.
func (*ReportRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_report_proto_rawDescGZIP(), []int{0}
}

func (x *ReportRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ReportRequest) GetReporterId() string {
	if x != nil {
		return x.ReporterId
	}
	return ""
}

func (x *ReportRequest) GetReportedUserId() string {
	if x != nil {
		return x.ReportedUserId
	}
	return ""
}

func (x *ReportRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *ReportRequest) GetChatLogsJson() string {
	if x != nil {
		return x.ChatLogsJson
	}
	return ""
}

type ReportResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Success            bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message            string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	CurrentReportCount int32                  `protobuf:"varint,3,opt,name=current_report_count,json=currentReportCount,proto3" json:"current_report_count,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ReportResponse) Reset() {
	*x = ReportResponse{}
	mi := &file_api_proto_v1_report_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportResponse) ProtoMessage() {}

func (x *ReportResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_report_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportResponse.ProtoReflect.Descriptor instead.
func (*ReportResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_report_proto_rawDescGZIP(), []int{1}
}

func (x *ReportResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ReportResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ReportResponse) GetCurrentReportCount() int32 {
	if x != nil {
		return x.CurrentReportCount
	}
	return 0
}

var File_api_proto_v1_report_proto protoreflect.FileDescriptor

const file_api_proto_v1_report_proto_rawDesc = "" +
	"\n" +
	"\x19api/proto/v1/report.proto\x12\agrpc.v1\"\xb7\x01\n" +
	"\rReportRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x1f\n" +
	"\vreporter_id\x18\x02 \x01(\tR\n" +
	"reporterId\x12(\n" +
	"\x10reported_user_id\x18\x03 \x01(\tR\x0ereportedUserId\x12\x16\n" +
	"\x06reason\x18\x04 \x01(\tR\x06reason\x12$\n" +
	"\x0echat_logs_json\x18\x05 \x01(\tR\fchatLogsJson\"v\n" +
	"\x0eReportResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x120\n" +
	"\x14current_report_count\x18\x03 \x01(\x05R\x12currentReportCount2P\n" +
	"\rReportService\x12?\n" +
	"\fSubmitReport\x12\x16.grpc.v1.ReportRequest\x1a\x17.grpc.v1.ReportResponseB:Z8github.com/b1g-nguyx/strangerchat-backend/internal/pb/v1b\x06proto3"

var (
	file_api_proto_v1_report_proto_rawDescOnce sync.Once
	file_api_proto_v1_report_proto_rawDescData []byte
)

func file_api_proto_v1_report_proto_rawDescGZIP() []byte {
	file_api_proto_v1_report_proto_rawDescOnce.Do(func() {
		file_api_proto_v1_report_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_v1_report_proto_rawDesc), len(file_api_proto_v1_report_proto_rawDesc)))
	})
	return file_api_proto_v1_report_proto_rawDescData
}

var file_api_proto_v1_report_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_proto_v1_report_proto_goTypes = []any{
	(*ReportRequest)(nil),  // 0: grpc.v1.ReportRequest
	(*ReportResponse)(nil), // 1: grpc.v1.ReportResponse
}
var file_api_proto_v1_report_proto_depIdxs = []int32{
	0, // 0: grpc.v1.ReportService.SubmitReport:input_type -> grpc.v1.ReportRequest
	1, // 1: grpc.v1.ReportService.SubmitReport:output_type -> grpc.v1.ReportResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_proto_v1_report_proto_init() }
func file_api_proto_v1_report_proto_init() {
	if File_api_proto_v1_report_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_v1_report_proto_rawDesc), len(file_api_proto_v1_report_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_v1_report_proto_goTypes,
		DependencyIndexes: file_api_proto_v1_report_proto_depIdxs,
		MessageInfos:      file_api_proto_v1_report_proto_msgTypes,
	}.Build()
	File_api_proto_v1_report_proto = out.File
	file_api_proto_v1_report_proto_goTypes = nil
	file_api_proto_v1_report_proto_depIdxs = nil
}
